{% set name = "xopen" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2fd9f537d96c6fb2f0bfed2c5ea133d8961dcef0baa3d8c388cb8bea2af5b090

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - bz2file   # [py27]
    - pip
    - python
    - pytest
    - setuptools_scm
  run:
    - bz2file   # [py27]
    - python

test:
  imports:
    - xopen

about:
  home: https://github.com/marcelm/xopen/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open compressed files transparently in Python
  doc_url: https://github.com/marcelm/xopen/
  dev_url: https://github.com/marcelm/xopen/

extra:
  recipe-maintainers:
    - marcelm
    - rhpvorderman
