{% set name = "xopen" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c34127651e538cfdd67ec8016a6505ba386158bbfe3f615e105d49027d5968e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - pytest
    - setuptools_scm
  run:
    - python
    - python-isal >=1.6.1  # [x86_64 or aarch64]
    - python-zlib-ng >=0.4.1  # [x86_64]
    - pigz
    - pbzip2  # [unix]
    - zstandard
    - zstd

test:
  imports:
    - xopen

about:
  home: https://github.com/pycompression/xopen/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open compressed files transparently in Python
  doc_url: https://github.com/pycompression/xopen/
  dev_url: https://github.com/pycompression/xopen/

extra:
  recipe-maintainers:
    - corneliusroemer
    - marcelm
    - rhpvorderman
